// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c739e86d-a28b-4d2f-9338-af1f72c68395",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_ldg9ve6zw",
    "aws_user_pools_web_client_id": "3il6t0ndg9ouur6acim917njnv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2t63s45o2vhzbmfb37lwasemny.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
